### ISSUE TITLE
Open existing Terraform Issue [516]: [Storing sensitive values in state files]

### ISSUE THREAD

**Issue by mwarkentin** [opentffoundation/roadmap#19]
Sorry.. I had to.. I've been following this issue for probably over half a decade. 😆 

[#516 Storing sensitive values in state files](https://github.com/hashicorp/terraform/issues/516)

**Comment by cube2222** [comment]
Haha, state file encryption is actually one of the first items we wanna put an RFC up for.

**Comment by StephanHCB** [comment]
I already made a PR for full client side state encryption for all backends except the extended backends 2 years ago. 

I am planning to submit it as a "stale PR" in the next days.

Based on this 5 year old issue called, aptly, "Proposal: State Encryption": https://github.com/hashicorp/terraform/issues/9556

Technical description / Proposal for my solution was here: https://github.com/hashicorp/terraform/issues/9556#issuecomment-826341937

Unmerged pull request is here:
https://github.com/hashicorp/terraform/pull/28603

I have tried it extensively with state stored on Azure storage accounts, and it is known to work in this scenario.

**Comment by StephanHCB** [comment]
> Haha, state file encryption is actually one of the first items we wanna put up an RFC for.

Hi! Please check out https://github.com/opentffoundation/roadmap/issues/23

**Comment by cube2222** [comment]
@StephanHCB Hey!

We'd appreciate it a lot if you could resubmit this as an RFC on the OpenTF project, once the repo is open, as it seems you've thought this through a lot.

I did a rudimentary working PoC of this during the last weekend as well with pbkdf2 and aead, to better understand the problem domain.

Anyway, one idea we've had and discussed internally, was possibly using [SOPS](https://github.com/getsops/sops) under the hood, as it already solves the use case of encrypting json/yaml files really well (and what is a state file if not that). The advantages would be

1. encrypting only the sensitive values has a lower chance of breaking state backends that actually try to parse your state (and I suppose there might be some that do), as opposed to sending an encrypted blob of the whole json
2. out of the box supporting all encryption backends that sops integrates with.

I'd love to hear your thoughts on that.

**Comment by roni-frantchi** [comment]
Hey @mwarkentin !  
Now that [OpenTF](https://github.com/opentffoundation/roadmap/blob/main/github.com/opentffoundation/opentf) is available, the project's roadmap has moved there, and will be managed via GitHub [issues](https://github.com/opentffoundation/roadmap/issues) and [milestones](https://github.com/opentffoundation/roadmap/milestones) on that repo 🚀

Looks like this issue already has its twin in https://github.com/opentffoundation/opentf/issues/297 (thanks @StephanHCB 😉 )  

So I'll be closing this one instead of moving it like the others.  
Looking forward to seeing you there!
